# permissions for end users to edit wateringalarms.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wateringalarm-editor-role
rules:
- apiGroups:
  - alarm.ricardoptcosta.github.io
  resources:
  - wateringalarms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alarm.ricardoptcosta.github.io
  resources:
  - wateringalarms/status
  verbs:
  - get
