apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wateringalarms.ric.com
spec:
  group: ric.com
  names:
    kind: WateringAlarm
    plural: wateringalarms
    listKind: WateringAlarmList
    singular: wateringalarm
  scope: Namespaced
  versions:
  - name: v1
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              plant:
                type: string
                description: Type of plant
              timeinterval:
                type: integer
                description: Interval between watering
    additionalPrinterColumns:
      - name: Plant
        jsonPath: .spec.plant
        type: string
      - name: TimeInterval
        jsonPath: .spec.timeinterval
        type: string
      - name: Age
        jsonPath: .metadata.creationTimestamp
        type: date